spring:
  kafka:
    consumer:
      group-id: spring-errors-group
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
    listener:
      log-container-config: true
logging:
  level:
    org.springframework.kafka.listener: warn
    org.apache.kafka.clients.consumer: warn
