spring:
  kafka:
    consumer:
      group-id: my-group
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
    listener:
      ack-mode: manual
      poll-timeout: 500ms # a short interval to minimize wait duration for processing seeks. Seeks are not executed until a poll (is this true?)
      log-container-config: true
logging:
  level:
    org.springframework.kafka.listener: debug
